### ISSUE TITLE
Internal Server Error - minimale Anwendung

### ISSUE THREAD

**Issue by LordRazor** [danieldaeschle/swapy#1]
```
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Feb/2018 18:20:05] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wsgi.py", line 48, in <lambda>
    return update_wrapper(lambda *a: f(*a)(*a[-2:]), f)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\swapy\_utils.py", line 372, in application
    result = urls.dispatch(dispatch)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\routing.py", line 1437, in dispatch
    return view_func(endpoint, args)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\swapy\_utils.py", line 365, in dispatch
    req.secure_cookie.save_cookie(ret)
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\swapy\wrappers.py", line 56, in secure_cookie
    return self.get_secure_cookie()
  File "C:\Users\Tester\AppData\Local\Programs\Python\Python36\lib\site-packages\swapy\wrappers.py", line 66, in get_secure_cookie
    raise Exception('\'secret_key\' value must be set in environment')
Exception: 'secret_key' value must be set in environment
```
*Was genau habe ich getan?* Eine minimale Anwendung gestartet (wie im Wiki beschrieben) und per Browser angesteuert
<br />
*Wie wirkt es sich aus?* Fehlermeldung in Konsole, Internal Server Error im Browser, Anwendung läuft danach weiter

OS: Windows 10 64-bit

**Comment by danieldaeschle** [comment]
Commit [0c7339a](https://github.com/danieldaeschle/swapy/commit/0c7339ad26cf1f3b3f53a7e9881bd233895cd2dd) fixes the issue.
